### ISSUE TITLE
Reg Part 1: External users can't upload stat dec docs [8]

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/cas-registration#1964]
Describe the Bug: 
External users are unable to upload statutory declaration documents as part of the Registration Part 1 flow because our next server now has a body size limit of 1 MB, which isn't large enough for document upload.

Probability (how likely the bug is to happen, scored from 1-5): 4
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 4
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:
1. Try to upload a statutory declaration document (in Operations tile) larger than 1 MB file size
2. Fail.

Screenshots:

Additional information:

- have received report that it's currently affecting 1 operator

Error log from [frontend pod](https://console.apps.silver.devops.gov.bc.ca/k8s/ns/d193ca-prod/pods/cas-registration-frontend-855f8ccc8c-mssc7/logs):

```
h [Error]: Body exceeded 1 MB limit.
To configure the body size limit for Server Actions, see: https://nextjs.org/docs/app/api-reference/functions/server-actions#size-limitation
at /usr/src/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:15:7358
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async rm (/usr/src/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:15:6342)
at async rq (/usr/src/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:18:1249)
at async doRender (/usr/src/app/node_modules/next/dist/server/base-server.js:1395:30)
at async cacheEntry.responseCache.get.routeKind (/usr/src/app/node_modules/next/dist/server/base-server.js:1556:28)
at async NextNodeServer.renderToResponseWithComponentsImpl (/usr/src/app/node_modules/next/dist/server/base-server.js:1464:28)
at async NextNodeServer.renderPageComponent (/usr/src/app/node_modules/next/dist/server/base-server.js:1861:24)
at async NextNodeServer.renderToResponseImpl (/usr/src/app/node_modules/next/dist/server/base-server.js:1899:32)
at async NextNodeServer.pipeImpl (/usr/src/app/node_modules/next/dist/server/base-server.js:912:25) {
statusCode: 413
}
```

- initial findings: in dev I wasn't able to upload a 1MB PDF file (got the same error message in dev as above); a 50KB PDF file upload was successful but slow (approx. 5 seconds)
- the bug that the external user reported was that the "Submit" button is greyed out for them, which is the only UI indicator we have that the file is in the process of being uploaded. Maybe the upload is timing out on file sizes that should be considered reasonable?

**Comment by BCerki** [comment]
~Maybe this became a problem when we moved to Next 14?
- https://github.com/vercel/next.js/discussions/57973
- https://github.com/vercel/next.js/discussions/53989
